package io.objectbox.codemodifier.test;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Backlink;

import java.util.List;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.BoxStore;
import io.objectbox.relation.ToMany;

@Entity
public class Customer {

    @Id
    long id;

    String name;

    @Backlink(to = "customerId")
    List<Order> orders = new ToMany<>(this, Customer_.orders);

    /** Used to resolve relations */
    @Internal
    @Generated(1307364262)
    transient BoxStore __boxStore;

    @Generated(829478790)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public Customer(long id, String name) {
        this.id = id;
        this.name = name;
    }

    @Generated(60841032)
    public Customer() {
    }
}
