package io.objectbox.codemodifier.test;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Relation;

import java.util.List;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.Box;
import io.objectbox.BoxStore;
import io.objectbox.exception.DbDetachedException;

@Entity
public class Customer {

    @Id
    long id;

    String name;

    @Relation(idProperty = "customerId")
    List<Order> orders;

    /** Used to resolve relations */
    @Internal
    @Generated(1307364262)
    transient BoxStore __boxStore;

    @Generated(829478790)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public Customer(long id, String name) {
        this.id = id;
        this.name = name;
    }

    @Generated(60841032)
    public Customer() {
    }

    /**
     * To-many relationship, resolved on first access (and after reset).
     * Changes to to-many relations are not persisted, make changes to the target entity.
     */
    @Generated(1958088637)
    public List<Order> getOrders() {
        if (orders == null) {
            final BoxStore boxStore = this.__boxStore;
            if (boxStore == null) {
                throw new DbDetachedException();
            }
            Box<Order> box = boxStore.boxFor(Order.class);
            int targetTypeId = boxStore.getEntityTypeIdOrThrow(Order.class);
            List<Order> ordersNew = box.getBacklinkEntities(targetTypeId, Order_.customerId, id);
            synchronized (this) {
                if (orders == null) {
                    orders = ordersNew;
                }
            }
        }
        return orders;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    @Generated(1446109810)
    public synchronized void resetOrders() {
        orders = null;
    }
}
