package io.objectbox.codemodifier.test.one;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.relation.ToOne;

import java.util.List;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.BoxStore;

@Entity
public class OnePackage {

    @Id
    long id;

    ToOne<OtherPackage> other = new ToOne<>(this, OnePackage_.other);

    /** Used to resolve relations */
    @Internal
    @Generated(1307364262)
    transient BoxStore __boxStore;

    @Generated(497747385)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public OnePackage(long id, long otherId) {
        this.id = id;
        this.other.setTargetId(otherId);
    }

    @Generated(1279500063)
    public OnePackage() {
    }

}
