package io.objectbox.test.entityannotation;

import java.util.List;

import io.objectbox.BoxStore;
import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Index;
import io.objectbox.annotation.Backlink;
import io.objectbox.annotation.apihint.Internal;

/**
 * Entity mapped to table "CUSTOMER".
 */
@Entity
public class Customer {

    @Id
    long id;

    @Index
    String name;

    @Backlink
    List<Order> orders;

    /** Used to resolve relations */
    @Internal
    @Generated(hash = 1307364262)
    transient BoxStore __boxStore;

    @Generated(hash = 60841032)
    public Customer() {
    }

    @Generated(hash = 829478790)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public Customer(long id, String name) {
        this.id = id;
        this.name = name;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
