package io.objectbox.processor.test;

import java.util.List;

import io.objectbox.BoxStore;
import io.objectbox.Cursor;
import io.objectbox.Transaction;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.relation.ToMany;
// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * ObjectBox generated Cursor implementation for "ToManyStandalone".
 * Note that this is a low-level class: usually you should stick to the Box class.
 */
public final class ToManyStandaloneCursor extends Cursor<ToManyStandalone> {
    @Internal
    static final class Factory implements CursorFactory<ToManyStandalone> {
        @Override
        public Cursor<ToManyStandalone> createCursor(Transaction tx, long cursorHandle, BoxStore boxStoreForEntities) {
            return new ToManyStandaloneCursor(tx, cursorHandle, boxStoreForEntities);
        }
    }

    private static final ToManyStandalone_.ToManyStandaloneIdGetter ID_GETTER = ToManyStandalone_.__ID_GETTER;



    public ToManyStandaloneCursor(Transaction tx, long cursor, BoxStore boxStore) {
        super(tx, cursor, ToManyStandalone_.__INSTANCE, boxStore);
    }

    @Override
    public final long getId(ToManyStandalone entity) {
        return ID_GETTER.getId(entity);
    }

    /**
     * Puts an object into its box.
     *
     * @return The ID of the object within its box.
     */
    @Override
    public final long put(ToManyStandalone entity) {
        Long id = entity.id;
        long __assignedId = collect004000(cursor, id != null ? id: 0, PUT_FLAG_FIRST | PUT_FLAG_COMPLETE,
                0, 0, 0, 0,
                0, 0, 0, 0);

        entity.id = __assignedId;

        attachEntity(entity);
        List<IdEntity> children = entity.children;
        if (children instanceof ToMany) {
            ToMany<IdEntity> toMany = (ToMany<IdEntity>) children;
            if (toMany.internalCheckApplyToDbRequired()) {
                Cursor<IdEntity> targetCursor = getRelationTargetCursor(IdEntity.class);
                try {
                    toMany.internalApplyToDb(this, targetCursor);
                } finally {
                    targetCursor.close();
                }
            }
        }
        return __assignedId;
    }

    private void attachEntity(ToManyStandalone entity) {
        // Transformer will create __boxStore field in entity and init it here:
        //entity.__boxStore = boxStoreForEntities;
    }

}
