/*
 * Copyright (C) 2017-2018 ObjectBox Ltd.
 *
 * This file is part of ObjectBox Build Tools.
 *
 * ObjectBox Build Tools is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * ObjectBox Build Tools is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ObjectBox Build Tools.  If not, see <http://www.gnu.org/licenses/>.
 */

package io.objectbox.generator.model;

@SuppressWarnings("unused")
public class Index extends PropertyOrderList {
    private String name;
    private boolean unique;
    private boolean nonDefaultName;
    /** Value mapped to a PropertyFlags constant in Java API. */
    private int type;
    /** Used to restrict index value length for String and byte[] if using value based index. */
    private int maxValueLength;

    public String getName() {
        return name;
    }

    public Index setName(String name) {
        this.name = name;
        this.nonDefaultName = name != null;
        return this;
    }

    public Index makeUnique() {
        unique = true;
        return this;
    }

    public boolean isUnique() {
        return unique;
    }

    public boolean isNonDefaultName() {
        return nonDefaultName;
    }

    /** used internally to know if name is generated by greenDAO */
    void setDefaultName(String name) {
        this.name = name;
        this.nonDefaultName = false;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public int getMaxValueLength() {
        return maxValueLength;
    }

    public void setMaxValueLength(int maxValueLength) {
        this.maxValueLength = maxValueLength;
    }
}
