package io.objectbox.codemodifier.test;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.apihint.Internal;

@Entity
public class Note {

    @Id
    private Long id;

    @Generated(1218261972)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public Note(Long id) {
        this.id = id;
    }

    @Generated(1272611929)
    public Note() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

}
