package io.objectbox.codemodifier.test;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.apihint.Internal;

@Entity
public class IdOnly {

    @Id
    long id;

    @Generated(hash = 433085191)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public IdOnly(long id) {
        this.id = id;
    }

    @Generated(hash = 203147900)
    public IdOnly() {
    }

}
