package io.objectbox.codemodifier.test;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;

@Entity
public class Note {

    @Id
    Long id;

    private String getterSetter;

    String noGetterSetter;

    protected String noGetterSetter2;

    public String noGetterSetter3;

    @Generated(hash = 1743248290)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public Note(Long id, String getterSetter, String noGetterSetter, String noGetterSetter2, String noGetterSetter3) {
        this.id = id;
        this.getterSetter = getterSetter;
        this.noGetterSetter = noGetterSetter;
        this.noGetterSetter2 = noGetterSetter2;
        this.noGetterSetter3 = noGetterSetter3;
    }

    @Generated(hash = 1272611929)
    public Note() {
    }

    public String getGetterSetter() {
        return getterSetter;
    }

    public void setGetterSetter(String getterSetter) {
        this.getterSetter = getterSetter;
    }

}
