package io.objectbox.codemodifier.test;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.apihint.Internal;

@Entity
public class Note {

    @Id
    private Long id;

    private String string;
    private int newInt;

    @Generated(hash = 1827698325)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public Note(Long id, String string, int newInt) {
        this.id = id;
        this.string = string;
        this.newInt = newInt;
    }

    @Generated(hash = 1272611929)
    public Note() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getString() {
        return string;
    }

    public void setString(String string) {
        this.string = string;
    }

    public int getNewInt() {
        return newInt;
    }

    public void setNewInt(int newInt) {
        this.newInt = newInt;
    }

}
