package io.objectbox.codemodifier.test;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;

@Entity
public class Note {

    @Id
    private String id;

    @Generated(hash = 1453938228)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public Note(String id) {
        this.id = id;
    }

    @Generated(hash = 1272611929)
    public Note() {
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

}
